name: base # environment name
channels: # package channels (the ones that are declared with -c flag)
  - https://conda.rcp.epfl.ch/pkgs/main
  - https://conda.rcp.epfl.ch/pkgs/free
  - https://conda.rcp.epfl.ch/nvidia
  - https://conda.rcp.epfl.ch/pytorch
  - pyg
dependencies: # desired packages, add or remove to satisfy youre requirements
  - python=3.10
  - pytorch=2.1.1 
  - torchvision=0.16.1
  - torchaudio=2.1.1
  - pytorch-cuda=11.8
  - pyg
  - scikit-learn
  - scipy
  - numpy
  - matplotlib
  - jupyterlab
  - pandas
