name: base # environment name
channels: # package channels (the ones that are declared with -c flag)
  - https://conda.rcp.epfl.ch/pkgs/main
  - https://conda.rcp.epfl.ch/pkgs/free
  - https://conda.rcp.epfl.ch/nvidia
dependencies: # desired packages, add or remove to satisfy youre requirements
  - python=3.12
  - scikit-learn
  - scipy
  - numpy
  - matplotlib
  - jupyterlab
  - pandas
  - networkx
  - pip:
    - torch==2.10.0
    - torchvision==0.25.0
    - torchaudio==2.10.0
    - pyg_lib 
    - torch_scatter 
    - torch_sparse 
    - torch_cluster 
    - torch_spline_conv
    - torch_geometric
    - wandb
    

